# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 04:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreastHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=200)),
                ('procedure', models.CharField(max_length=200)),
                ('mammogram', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=200)),
                ('support', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=200)),
                ('support', models.CharField(max_length=200)),
                ('change', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
                ('careflight', models.BooleanField()),
                ('location', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Maternity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('frequency', models.CharField(max_length=200)),
                ('health', models.CharField(max_length=200)),
                ('nicu', models.BooleanField()),
                ('reason', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Orthopedics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
                ('treatment', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('admin', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='orthopedics',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
        migrations.AddField(
            model_name='maternity',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
        migrations.AddField(
            model_name='bss',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
        migrations.AddField(
            model_name='breasthealth',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
    ]
