# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20171102_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('admin', models.IntegerField(default=0)),
                ('survey', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
