# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 22:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_login_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastHealth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('center', models.CharField(max_length=200)),
                ('procedure', models.CharField(max_length=200)),
                ('mammogram', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=200)),
                ('support', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BSS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=200)),
                ('support', models.CharField(max_length=200)),
                ('change', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=200)),
                ('careflight', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Orthopedics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=200)),
                ('treatment', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('admin', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('survey', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Login_User',
        ),
        migrations.AlterField(
            model_name='maternity',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='orthopedics',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
        migrations.AddField(
            model_name='bss',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
        migrations.AddField(
            model_name='breasthealth',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
    ]
