# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20171115_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='careflight',
            field=models.BooleanField(),
        ),
    ]
