branch-defaults:
  default:
    environment: testEnv3
    group_suffix: null
global:
  application_name: test3
  branch: null
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
