branch-defaults:
  default:
    environment: testEnv3
    group_suffix: null
  master:
    environment: Survey-env
    group_suffix: null
environment-defaults:
  Survey-env:
    branch: null
    repository: null
  testEnv3:
    branch: null
    repository: null
global:
  application_name: survey
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
