branch-defaults:
  master:
    environment: survey2-env
environment-defaults:
  survey2-env:
    branch: null
    repository: null
global:
  application_name: survey2
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
